import type {
  NormalizedContext,
  NormalizedCommandSet,
  NormalizedCommand,
  NormalizedExit,
  Option,
  Argument,
  JsonSchema,
  Components,
} from "../types.js";

export interface TypeScriptGeneratorOptions {
  emitTypes?: boolean;
  emitClient?: boolean;
  emitValidators?: boolean;
  emitProgram?: boolean;
}

export interface TypeScriptOutput {
  [filename: string]: string;
}

export function generateTypeScript(
  ctx: NormalizedContext,
  options: TypeScriptGeneratorOptions = {},
): TypeScriptOutput {
  const {
    emitTypes = true,
    emitClient = true,
    emitValidators = true,
    emitProgram = true,
  } = options;

  const output: TypeScriptOutput = {
    "index.ts": generateIndex(ctx, { emitProgram }),
    "types.ts": emitTypes ? generateTypes(ctx) : "// types generation disabled\nexport {};\n",
    "commands.ts": emitClient ? generateCommands(ctx) : "// client generation disabled\nexport {};\n",
    "schemas.ts": emitValidators ? generateSchemas(ctx) : "// validators generation disabled\nexport {};\n",
  };

  if (emitProgram) {
    output["program.ts"] = generateProgram(ctx);
  }

  return output;
}

function generateIndex(
  ctx: NormalizedContext,
  opts: { emitProgram: boolean },
): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push('export * from "./types.js";');
  lines.push('export * from "./commands.js";');
  lines.push('export * from "./schemas.js";');
  if (opts.emitProgram) {
    lines.push('export { createProgram } from "./program.js";');
    lines.push('export type { CommandHandlers } from "./program.js";');
  }
  lines.push("");
  return lines.join("\n");
}

function generateTypes(ctx: NormalizedContext): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push("");

  for (const cs of ctx.commandSets) {
    for (const cmd of cs.commands) {
      generateCommandTypes(cmd, cs, lines, ctx.components);
    }
  }

  if (ctx.components.schemas) {
    for (const [name, schema] of Object.entries(ctx.components.schemas)) {
      generateSchemaType(name, schema, lines);
    }
  }

  return lines.join("\n");
}

function generateCommandTypes(
  cmd: NormalizedCommand,
  cs: NormalizedCommandSet,
  lines: string[],
  components: Components,
): void {
  const prefix = toPascalCase(cmd.id);

  // Arguments type
  if (cmd.arguments.length > 0) {
    lines.push(`export interface ${prefix}Args {`);
    for (const arg of cmd.arguments) {
      const optional = arg.required ? "" : "?";
      const tsType = arg.variadic ? "string[]" : jsonSchemaToTs(arg.schema);
      lines.push(`  ${toCamelCase(arg.name)}${optional}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");
  }

  // Options type
  if (cmd.options.length > 0) {
    lines.push(`export interface ${prefix}Options {`);
    for (const opt of cmd.options) {
      const optional = opt.required ? "" : "?";
      const tsType = jsonSchemaToTs(opt.schema);
      lines.push(`  ${toCamelCase(opt.name)}${optional}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");
  }

  if (cmd.exits.length > 0) {
    const exitCodes = cmd.exits.map((e) => e.exitCode);
    lines.push(`export type ${prefix}ExitCode = ${exitCodes.join(" | ")};`);
    lines.push("");

    const resultVariants: string[] = [];
    for (const exit of cmd.exits) {
      const variant = buildExitResultVariant(exit, prefix, components);
      resultVariants.push(variant);
    }
    lines.push(`export type ${prefix}ExitResult =`);
    lines.push(`  ${resultVariants.join("\n  | ")};`);
    lines.push("");
  }
}

function buildExitResultVariant(
  exit: NormalizedExit,
  prefix: string,
  components: Components,
): string {
  const parts: string[] = [`exitCode: ${exit.exitCode}`];

  if (exit.stdout) {
    const type = resolveOutputType(exit.stdout.schema, components);
    const opt = exit.stdout.required === false ? "?" : "";
    parts.push(`stdout${opt}: ${type}`);
  }

  if (exit.stderr) {
    const type = resolveOutputType(exit.stderr.schema, components);
    const opt = exit.stderr.required === false ? "?" : "";
    parts.push(`stderr${opt}: ${type}`);
  }

  return `{ ${parts.join("; ")} }`;
}

function resolveOutputType(
  schema: JsonSchema | undefined,
  components: Components,
): string {
  if (!schema) return "unknown";
  if (schema.$ref) {
    const name = refToTypeName(schema.$ref);
    return name;
  }
  return jsonSchemaToTs(schema);
}

function generateCommands(ctx: NormalizedContext): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push('import { execFile } from "node:child_process";');
  lines.push('import { promisify } from "node:util";');
  lines.push("");
  lines.push("const execFileAsync = promisify(execFile);");
  lines.push("");

  lines.push("export interface ExecResult {");
  lines.push("  exitCode: number;");
  lines.push("  stdout: string;");
  lines.push("  stderr: string;");
  lines.push("}");
  lines.push("");

  for (const cs of ctx.commandSets) {
    for (const cmd of cs.commands) {
      generateCommandFunction(cmd, cs, lines);
    }
  }

  return lines.join("\n");
}

function generateCommandFunction(
  cmd: NormalizedCommand,
  cs: NormalizedCommandSet,
  lines: string[],
): void {
  const funcName = toCamelCase(cmd.fullId);
  const prefix = toPascalCase(cmd.id);
  const hasArgs = cmd.arguments.length > 0;
  const hasOpts = cmd.options.length > 0;

  const params: string[] = ["executable: string"];
  if (hasArgs) params.push(`args: import("./types.js").${prefix}Args`);
  if (hasOpts) params.push(`options?: Partial<import("./types.js").${prefix}Options>`);

  lines.push(`export async function ${funcName}(`);
  lines.push(`  ${params.join(",\n  ")},`);
  lines.push(`): Promise<ExecResult> {`);
  lines.push(`  const cmdArgs: string[] = ${JSON.stringify(cmd.path)};`);

  if (hasArgs) {
    for (const arg of cmd.arguments) {
      const name = toCamelCase(arg.name);
      if (arg.variadic) {
        lines.push(`  if (args.${name}) cmdArgs.push(...args.${name});`);
      } else {
        lines.push(`  if (args.${name} !== undefined) cmdArgs.push(String(args.${name}));`);
      }
    }
  }

  if (hasOpts) {
    lines.push("  if (options) {");
    for (const opt of cmd.options) {
      const name = toCamelCase(opt.name);
      const flag = `--${opt.name}`;
      if (opt.schema?.type === "boolean") {
        lines.push(`    if (options.${name}) cmdArgs.push("${flag}");`);
      } else {
        lines.push(`    if (options.${name} !== undefined) cmdArgs.push("${flag}", String(options.${name}));`);
      }
    }
    lines.push("  }");
  }

  lines.push("");
  lines.push("  try {");
  lines.push("    const result = await execFileAsync(executable, cmdArgs);");
  lines.push("    return { exitCode: 0, stdout: result.stdout, stderr: result.stderr };");
  lines.push("  } catch (err: unknown) {");
  lines.push("    const e = err as { code?: number; stdout?: string; stderr?: string };");
  lines.push("    return {");
  lines.push("      exitCode: typeof e.code === 'number' ? e.code : 1,");
  lines.push("      stdout: e.stdout ?? '',");
  lines.push("      stderr: e.stderr ?? '',");
  lines.push("    };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
}

function generateSchemas(ctx: NormalizedContext): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push("");

  if (!ctx.components.schemas || Object.keys(ctx.components.schemas).length === 0) {
    lines.push("export {};");
    lines.push("");
    return lines.join("\n");
  }

  lines.push("export const schemas = {");
  for (const [name, schema] of Object.entries(ctx.components.schemas)) {
    lines.push(`  ${name}: ${JSON.stringify(schema, null, 2).replace(/\n/g, "\n  ")},`);
  }
  lines.push("} as const;");
  lines.push("");

  for (const cs of ctx.commandSets) {
    for (const cmd of cs.commands) {
      const prefix = toPascalCase(cmd.id);
      const exitCodes = cmd.exits.map((e) => e.exitCode);
      lines.push(`export const ${toCamelCase(cmd.id)}ExitCodes = [${exitCodes.join(", ")}] as const;`);
    }
  }
  lines.push("");

  return lines.join("\n");
}

function generateSchemaType(
  name: string,
  schema: JsonSchema,
  lines: string[],
): void {
  if (schema.type === "object" && schema.properties) {
    lines.push(`export interface ${name} {`);
    const required = new Set(schema.required ?? []);
    for (const [prop, propSchema] of Object.entries(schema.properties)) {
      const opt = required.has(prop) ? "" : "?";
      const tsType = jsonSchemaToTs(propSchema);
      lines.push(`  ${prop}${opt}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");
  } else if (schema.type === "array" && schema.items) {
    lines.push(`export type ${name} = ${jsonSchemaToTs(schema.items)}[];`);
    lines.push("");
  } else if (schema.enum) {
    const values = schema.enum.map((v) =>
      typeof v === "string" ? `"${v}"` : String(v),
    );
    lines.push(`export type ${name} = ${values.join(" | ")};`);
    lines.push("");
  } else {
    lines.push(`export type ${name} = ${jsonSchemaToTs(schema)};`);
    lines.push("");
  }
}

function jsonSchemaToTs(schema?: JsonSchema): string {
  if (!schema) return "unknown";
  if (schema.$ref) return refToTypeName(schema.$ref);

  if (schema.oneOf) {
    return schema.oneOf.map(jsonSchemaToTs).join(" | ");
  }
  if (schema.anyOf) {
    return schema.anyOf.map(jsonSchemaToTs).join(" | ");
  }

  if (schema.enum) {
    return schema.enum
      .map((v) => (typeof v === "string" ? `"${v}"` : String(v)))
      .join(" | ");
  }

  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return `${jsonSchemaToTs(schema.items)}[]`;
    case "object":
      if (schema.properties) {
        const required = new Set(schema.required ?? []);
        const props = Object.entries(schema.properties)
          .map(([k, v]) => {
            const opt = required.has(k) ? "" : "?";
            return `${k}${opt}: ${jsonSchemaToTs(v)}`;
          })
          .join("; ");
        return `{ ${props} }`;
      }
      if (
        schema.additionalProperties === true ||
        typeof schema.additionalProperties === "object"
      ) {
        return "Record<string, unknown>";
      }
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function refToTypeName(ref: string): string {
  const parts = ref.split("/");
  return parts[parts.length - 1];
}

function toPascalCase(str: string): string {
  return str
    .split(/[.\-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

const JS_RESERVED = new Set([
  "break", "case", "catch", "class", "const", "continue", "debugger",
  "default", "delete", "do", "else", "export", "extends", "false",
  "finally", "for", "function", "if", "import", "in", "instanceof",
  "let", "new", "null", "return", "super", "switch", "this", "throw",
  "true", "try", "typeof", "undefined", "var", "void", "while", "with",
  "yield", "enum", "await", "implements", "interface", "package",
  "private", "protected", "public", "static",
]);

function safeIdentifier(name: string): string {
  const camel = toCamelCase(name);
  return JS_RESERVED.has(camel) ? `${camel}Arg` : camel;
}

// ─── program.ts generator ───────────────────────────────────────

function generateProgram(ctx: NormalizedContext): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by cli-contracts. Do not edit.");
  lines.push('import { Command } from "commander";');
  lines.push("");

  // Build the CommandHandlers interface
  lines.push("export interface CommandHandlers {");
  for (const cs of ctx.commandSets) {
    for (const cmd of cs.commands) {
      const handlerName = toCamelCase(cmd.id);
      const sig = buildHandlerSignature(cmd);
      lines.push(`  ${handlerName}: ${sig};`);
    }
  }
  lines.push("}");
  lines.push("");

  // Build createProgram function
  lines.push("export function createProgram(");
  lines.push("  handlers: CommandHandlers,");
  lines.push("  version: string,");
  lines.push("): Command {");
  lines.push("  const program = new Command();");

  // Assumes single command set for program name; use first
  const primaryCs = ctx.commandSets[0];
  lines.push(`  program`);
  lines.push(`    .name(${JSON.stringify(primaryCs.executable)})`);
  lines.push(`    .version(version, "-V, --version")`);
  lines.push(
    `    .description(${JSON.stringify(primaryCs.summary ?? ctx.info.description ?? "")});`,
  );
  lines.push("");

  for (const opt of primaryCs.globalOptions) {
    const skipBuiltins = ["version", "help"];
    if (skipBuiltins.includes(opt.name)) continue;
    const optFlag = buildOptionFlag(opt);
    const desc = JSON.stringify(opt.description ?? "");
    const def = opt.schema?.default;
    if (def !== undefined) {
      const defValue = commanderDefaultValue(def, opt.schema?.type);
      lines.push(
        `  program.option(${JSON.stringify(optFlag)}, ${desc}, ${defValue});`,
      );
    } else {
      lines.push(
        `  program.option(${JSON.stringify(optFlag)}, ${desc});`,
      );
    }
  }
  lines.push("");

  // Commands
  for (const cs of ctx.commandSets) {
    for (const cmd of cs.commands) {
      generateProgramCommand(cmd, lines);
    }
  }

  lines.push("  return program;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function buildHandlerSignature(cmd: NormalizedCommand): string {
  const params: string[] = [];

  for (const arg of cmd.arguments) {
    const type = arg.variadic ? "string[]" : "string | undefined";
    params.push(`${safeIdentifier(arg.name)}: ${type}`);
  }

  if (cmd.options.length > 0) {
    const optFields = cmd.options.map((o) => {
      const type = o.schema?.type === "boolean" ? "boolean" : "string";
      return `${toCamelCase(o.name)}?: ${type}`;
    });
    params.push(`options: { ${optFields.join("; ")} }`);
  }

  params.push("parentOpts: Record<string, unknown>");

  return `(${params.join(", ")}) => Promise<void>`;
}

function generateProgramCommand(
  cmd: NormalizedCommand,
  lines: string[],
): void {
  const handlerName = toCamelCase(cmd.id);
  const cmdPath = cmd.path.join(" ");

  lines.push(`  program`);
  lines.push(`    .command(${JSON.stringify(cmdPath)})`);
  lines.push(`    .description(${JSON.stringify(cmd.summary)})`);

  // Arguments
  for (const arg of cmd.arguments) {
    const token = arg.variadic
      ? arg.required ? `<${arg.name}...>` : `[${arg.name}...]`
      : arg.required ? `<${arg.name}>` : `[${arg.name}]`;
    const desc = JSON.stringify(arg.description ?? "");
    lines.push(`    .argument(${JSON.stringify(token)}, ${desc})`);
  }

  for (const opt of cmd.options) {
    const flag = buildOptionFlag(opt);
    const desc = JSON.stringify(opt.description ?? "");
    const def = opt.schema?.default;
    if (def !== undefined) {
      const defValue = commanderDefaultValue(def, opt.schema?.type);
      lines.push(
        `    .option(${JSON.stringify(flag)}, ${desc}, ${defValue})`,
      );
    } else {
      lines.push(`    .option(${JSON.stringify(flag)}, ${desc})`);
    }
  }

  const argSafeNames = cmd.arguments.map((a) => safeIdentifier(a.name));
  const actionParams = [...argSafeNames];
  actionParams.push("opts");
  actionParams.push("cmd");

  lines.push(
    `    .action(async (${actionParams.join(", ")}) => {`,
  );
  const callArgs = [
    ...argSafeNames,
    cmd.options.length > 0 ? "opts" : "{}",
    "cmd.optsWithGlobals()",
  ];
  lines.push(
    `      await handlers.${handlerName}(${callArgs.join(", ")});`,
  );
  lines.push("    });");
  lines.push("");
}

function commanderDefaultValue(
  def: unknown,
  schemaType?: string | string[],
): string {
  if (typeof def === "boolean") return JSON.stringify(def);
  if (typeof def === "string") return JSON.stringify(def);
  // Commander expects string defaults for non-boolean options
  return JSON.stringify(String(def));
}

function buildOptionFlag(opt: Option): string {
  const parts: string[] = [];
  if (opt.aliases && opt.aliases.length > 0) {
    parts.push(`-${opt.aliases[0]}`);
  }
  const isBoolean = opt.schema?.type === "boolean";
  if (isBoolean) {
    parts.push(`--${opt.name}`);
  } else {
    const valueName = opt.valueName ?? "value";
    if (opt.repeatable) {
      parts.push(`--${opt.name} <${valueName}...>`);
    } else {
      parts.push(`--${opt.name} <${valueName}>`);
    }
  }
  return parts.join(", ");
}
