import { describe, it, expect } from "vitest";
import { resolve } from "node:path";
import { parseContractFile, parseContractString } from "../../../src/parser.js";
import { normalizeContract } from "../../../src/normalizer.js";
import { generateTypeScript } from "../../../src/generators/typescript.js";

const FIXTURES = resolve(import.meta.dirname, "../../fixtures");

describe("generateTypeScript program.ts", () => {
  it("generates program.ts when emitProgram is true", async () => {
    const doc = await parseContractFile(
      resolve(FIXTURES, "valid-contract.yaml"),
    );
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx, { emitProgram: true });

    expect(output).toHaveProperty("program.ts");
    expect(output["program.ts"]).toContain("Auto-generated by cli-contracts");
  });

  it("omits program.ts when emitProgram is false", async () => {
    const doc = await parseContractFile(
      resolve(FIXTURES, "valid-contract.yaml"),
    );
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx, { emitProgram: false });

    expect(output).not.toHaveProperty("program.ts");
  });

  it("exports createProgram and CommandHandlers", async () => {
    const doc = await parseContractFile(
      resolve(FIXTURES, "valid-contract.yaml"),
    );
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);

    expect(output["program.ts"]).toContain("export interface CommandHandlers");
    expect(output["program.ts"]).toContain("export function createProgram");
  });

  it("index.ts re-exports createProgram when program is emitted", async () => {
    const doc = await parseContractFile(
      resolve(FIXTURES, "valid-contract.yaml"),
    );
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx, { emitProgram: true });

    expect(output["index.ts"]).toContain('export { createProgram }');
    expect(output["index.ts"]).toContain('export type { CommandHandlers }');
  });

  it("registers all commands from the contract", async () => {
    const doc = await parseContractFile(
      resolve(FIXTURES, "valid-contract.yaml"),
    );
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);
    const program = output["program.ts"];

    expect(program).toContain('.command("users list")');
    expect(program).toContain('.command("users import")');
    expect(program).toContain('.command("logs filter")');
    expect(program).toContain('.command("tenants create")');
  });

  it("generates handler entries for each command", async () => {
    const doc = await parseContractFile(
      resolve(FIXTURES, "valid-contract.yaml"),
    );
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);
    const program = output["program.ts"];

    expect(program).toContain("usersList:");
    expect(program).toContain("usersImport:");
    expect(program).toContain("logsFilter:");
    expect(program).toContain("tenantsCreate:");
  });

  it("generates option flags from contract", async () => {
    const doc = await parseContractFile(
      resolve(FIXTURES, "valid-contract.yaml"),
    );
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);
    const program = output["program.ts"];

    expect(program).toContain("-f, --format");
    expect(program).toContain("-l, --limit");
    expect(program).toContain("-n, --dry-run");
  });

  it("generates argument declarations from contract", async () => {
    const doc = await parseContractFile(
      resolve(FIXTURES, "valid-contract.yaml"),
    );
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);
    const program = output["program.ts"];

    expect(program).toContain('<input>');
    expect(program).toContain('<name>');
  });

  it("generates global options", async () => {
    const doc = await parseContractFile(
      resolve(FIXTURES, "valid-contract.yaml"),
    );
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);
    const program = output["program.ts"];

    expect(program).toContain("-v, --verbose");
  });

  it("uses safe identifiers for reserved words", () => {
    const doc = parseContractString(`
cli_contracts: 0.1.0
info:
  title: T
  version: 0.1.0
command_sets:
  foo:
    commands:
      compare:
        summary: Compare.
        arguments:
          - name: old
            required: true
            schema:
              type: string
          - name: new
            required: false
            schema:
              type: string
        exits:
          '0':
            description: OK.
`);
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);
    const program = output["program.ts"];

    expect(program).toContain("newArg");
    // Action params and handler call should use newArg, not bare `new`
    expect(program).toContain("(old, newArg, opts, cmd)");
    expect(program).toContain("handlers.compare(old, newArg,");
  });

  it("handler signature and action arity match for command with no options", () => {
    const doc = parseContractString(`
cli_contracts: 0.1.0
info:
  title: T
  version: 0.1.0
command_sets:
  foo:
    commands:
      check:
        summary: Run full verification pipeline for CI.
        exits:
          '0':
            description: All checks passed.
`);
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);
    const program = output["program.ts"];

    // Signature must include options param even with no options
    expect(program).toContain(
      "check: (options: Record<string, never>, parentOpts: Record<string, unknown>) => Promise<void>",
    );
    // Action call must pass {} and parentOpts — matching the 2-arg signature
    expect(program).toContain("await handlers.check({}, cmd.optsWithGlobals())");
  });

  it("handler signature and action arity match for command with args but no options", () => {
    const doc = parseContractString(`
cli_contracts: 0.1.0
info:
  title: T
  version: 0.1.0
command_sets:
  foo:
    commands:
      deploy:
        summary: Deploy to target.
        arguments:
          - name: target
            required: true
            schema:
              type: string
        exits:
          '0':
            description: OK.
`);
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);
    const program = output["program.ts"];

    expect(program).toContain(
      "deploy: (target: string | undefined, options: Record<string, never>, parentOpts: Record<string, unknown>) => Promise<void>",
    );
    expect(program).toContain(
      "await handlers.deploy(target, {}, cmd.optsWithGlobals())",
    );
  });

  it("handler signature includes typed options for command with options", () => {
    const doc = parseContractString(`
cli_contracts: 0.1.0
info:
  title: T
  version: 0.1.0
command_sets:
  foo:
    commands:
      build:
        summary: Build the project.
        options:
          - name: watch
            schema:
              type: boolean
          - name: output-dir
            schema:
              type: string
        exits:
          '0':
            description: OK.
`);
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);
    const program = output["program.ts"];

    expect(program).toContain(
      "build: (options: { watch?: boolean; outputDir?: string }, parentOpts: Record<string, unknown>) => Promise<void>",
    );
    expect(program).toContain(
      "await handlers.build(opts, cmd.optsWithGlobals())",
    );
  });

  it("minimal contract (no args, no options) generates compilable program", async () => {
    const doc = await parseContractFile(
      resolve(FIXTURES, "minimal-contract.yaml"),
    );
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);
    const program = output["program.ts"];

    // Signature and call site must have same arity (2)
    expect(program).toContain(
      "hello: (options: Record<string, never>, parentOpts: Record<string, unknown>) => Promise<void>",
    );
    expect(program).toContain("await handlers.hello({}, cmd.optsWithGlobals())");
  });

  it("description comes from contract summary", () => {
    const doc = parseContractString(`
cli_contracts: 0.1.0
info:
  title: T
  version: 0.1.0
command_sets:
  my-tool:
    summary: My awesome tool.
    commands:
      hello:
        summary: Say hello nicely.
        exits:
          '0':
            description: OK.
`);
    const ctx = normalizeContract(doc);
    const output = generateTypeScript(ctx);
    const program = output["program.ts"];

    expect(program).toContain('.name("my-tool")');
    expect(program).toContain('.description("My awesome tool.")');
    expect(program).toContain('.description("Say hello nicely.")');
  });
});
